trigger:
  branches:
    include:
      - main 

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: hometask_VAR
  ACR_LOGIN_SERVER: "myimagesvault.azurecr.io"
  #IMAGE_NAME: "hometask-image"
  #IMAGE_TAG: "$(Build.BuildId)"
  SERVICE_CON: "auth_to_azure_services"
  RESOURCE_GRP: "hometask_RG"
  #AKS_CLUSTER: "hometask_AKS_Cluster"

steps:
  - task: Docker@2
    inputs:
      containerRegistry: $SERVICE_CON
      repository: '$(ACR_LOGIN_SERVER)/$(IMAGE_NAME)'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(IMAGE_TAG)

  - task: Kubernetes@1
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: $SERVICE_CON
      azureResourceGroup: $RESOURCE_GRP
      kubernetesCluster: $AKS_CLUSTER
      command: 'apply'
      useConfigurationFile: true
      configuration: app.yaml
      