trigger:
  branches:
    include:
      - main 

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: hometask_VAR

steps:
  - task: Docker@2
    inputs:
      containerRegistry: $(TO_ACR_SERVICE_CON)
      repository: $(IMAGE_NAME)
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(IMAGE_TAG)

  - script: |
      echo "Substituting variables in app.yaml with sed"
      sed -i 's#{{ACR_LOGIN_SERVER}}#$(ACR_LOGIN_SERVER)#g' app.yaml
      sed -i 's#{{IMAGE_NAME}}#$(IMAGE_NAME)#g' app.yaml
      sed -i 's#{{IMAGE_TAG}}#$(IMAGE_TAG)#g' app.yaml
      sed -i 's#{{PUBLIC_IP}}#$(PUBLIC_IP)#g' app.yaml

  - task: Kubernetes@1
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: $(TO_RG_SERVICE_CON)
      azureResourceGroup: $(RESOURCE_GRP)
      kubernetesCluster: $(AKS_CLUSTER)
      command: 'apply'
      useConfigurationFile: true
      configuration: app.yaml
      