trigger:
  branches:
    include:
      - main 

pool:
  name: 'Default'
  demands: 'MyHomePC'

variables:
- group: hometask_VAR

steps:
  - task: Docker@2
    inputs:
      containerRegistry: $(ACR_SERVICE_CON)
      repository: $(ACR_LOGIN_SERVER)/$(IMAGE_NAME)
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(IMAGE_TAG)

  - task: Kubernetes@1
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: $(K8S_SERVICE_CON)
      azureResourceGroup: $(RESOURCE_GRP)
      kubernetesCluster: $(AKS_CLUSTER)
      command: 'apply'
      useConfigurationFile: true
      configuration: app.yaml
      